--!strict

return {
    curveAccelerateMax = { 0.9, 0.1, 1, 0.2 },
    curveAccelerateMid = { 1, 0, 1, 1 },
    curveAccelerateMin = { 0.8, 0, 0.78, 1 },
    curveDecelerateMax = { 0.1, 0.9, 0.2, 1 },
    curveDecelerateMid = { 0, 0, 0, 1 },
    curveDecelerateMin = { 0.33, 0, 0.1, 1 },
    curveEasyEaseMax = { 0.8, 0, 0.2, 1 },
    curveEasyEase = { 0.33, 0, 0.67, 1 },
    curveLinear = { 0, 0, 1, 1 },
}
